spring:
  redis:
    password: redis
#### 单实例模式 ####
    host: 127.0.0.1
    port: 6379
    database: 0
#### 哨兵模式 ####
#    sentinel:
#      master: mymaster
#      nodes: 127.0.0.1:26380,127.0.0.1:26381,127.0.0.1:26382
#      database: 0
#### 集群模式 ####
#    cluster:
#      nodes: 192.168.1.1:6379,192.168.1.2:6379,192.168.1.3:6379,192.168.1.4:6379,192.168.1.5:6379,192.168.1.6:6379

logging:
  level:
    "tk.gushizone": debug



